package level;

import java.util.HashMap;
import java.util.Map;

public class A1Words {
    public static Map<String, String> getWords() {
        Map<String, String> a1Words = new HashMap<>();

        a1Words.put("house", "ev");
        a1Words.put("book", "kitap");
        a1Words.put("table", "masa");
        a1Words.put("chair", "sandalye");
        a1Words.put("kalem", "pen");
        a1Words.put("kapı", "door");
        a1Words.put("window", "pencere");
        a1Words.put("car", "araba");
        a1Words.put("kedi", "cat");
        a1Words.put("dog", "köpek");
        a1Words.put("tree", "ağaç");
        a1Words.put("güneş", "sun");
        a1Words.put("moon", "ay");
        a1Words.put("star", "yıldız");
        a1Words.put("water", "su");
        a1Words.put("apple", "elma");
        a1Words.put("fruit", "meyve");
        a1Words.put("sokak", "street");
        a1Words.put("bird", "kuş");
        a1Words.put("top", "ball");
        a1Words.put("color", "renk");
        a1Words.put("sayı", "number");
        a1Words.put("clock", "saat");
        a1Words.put("gözlük", "glasses");
        a1Words.put("hat", "şapka");
        a1Words.put("umbrella", "şemsiye");
        a1Words.put("television", "televizyon");
        a1Words.put("phone", "telefon");
        a1Words.put("red", "kırmızı");
        a1Words.put("desk lamp", "masa lambası");
        a1Words.put("buzdolabı", "refrigerator");
        a1Words.put("kitaplık", "bookshelf");
        a1Words.put("whiteboard", "yazı tahtası");
        a1Words.put("shoe", "ayakkabı");
        a1Words.put("horse", "at");
        a1Words.put("gitar", "guitar");
        a1Words.put("sugar", "şeker");
        a1Words.put("radyo", "radio");
        a1Words.put("football", "futbol");
        a1Words.put("swimming", "yüzme");
        a1Words.put("gözlük kutusu", "glasses case");
        a1Words.put("pillow", "yastık");
        a1Words.put("train", "tren");
        a1Words.put("airplane", "uçak");
        a1Words.put("sky", "gökyüzü");
        a1Words.put("deniz", "sea");
        a1Words.put("pond", "gölet");
        a1Words.put("mountain", "dağ");
        a1Words.put("glasses cleaning spray", "gözlük temizleme spreyi");
        a1Words.put("umbrella stand", "şemsiye standı");
        a1Words.put("parfüm", "perfume");
        a1Words.put("necklace", "kolye");
        a1Words.put("tişört", "t-shirt");
        a1Words.put("classroom", "sınıf");
        a1Words.put("pencil sharpener", "kalemtraş");
        a1Words.put("paper", "kağıt");
        a1Words.put("student", "öğrenci");
        a1Words.put("teacher", "öğretmen");
        a1Words.put("notebook", "kitapçık");
        a1Words.put("small", "küçük");
        a1Words.put("big", "büyük");
        a1Words.put("writing", "yazı");
        a1Words.put("reading", "okuma");
        a1Words.put("colorful", "renkli");
        a1Words.put("black", "siyah");
        a1Words.put("white", "beyaz");
        a1Words.put("blue", "mavi");
        a1Words.put("green", "yeşil");
        a1Words.put("blonde", "sarışın");
        a1Words.put("brown", "kahverengi");
        a1Words.put("black-haired", "siyah saçlı");
        a1Words.put("wearing glasses", "gözlüklü");
        a1Words.put("sports shoes", "spor ayakkabı");
        a1Words.put("meal", "yemek");
        a1Words.put("breakfast", "kahvaltı");
        a1Words.put("lunch", "öğle yemeği");
        a1Words.put("dinner", "akşam yemeği");
        a1Words.put("sushi", "suşi");
        a1Words.put("pizza", "pizza");
        a1Words.put("hamburger", "hamburger");
        a1Words.put("sandwich", "sandviç");
        a1Words.put("coffee", "kahve");
        a1Words.put("tea", "çay");
        a1Words.put("milk", "süt");
        a1Words.put("fruit juice", "meyve suyu");
        a1Words.put("toy", "oyuncak");
        a1Words.put("movie", "film");
        a1Words.put("music", "müzik");
        a1Words.put("picture", "resim");
        a1Words.put("number", "sayı");
        a1Words.put("letter", "harf");
        a1Words.put("word", "kelime");
        a1Words.put("sentence", "cümle");
        a1Words.put("day", "gün");
        a1Words.put("week", "hafta");
        a1Words.put("year", "yıl");
        a1Words.put("bugün", "today");
        a1Words.put("yarın", "tomorrow");
        a1Words.put("dün", "yesterday");
        a1Words.put("dakika", "minute");
        a1Words.put("saniye", "second");
        a1Words.put("kamera", "camera");
        a1Words.put("bilgisayar", "computer");
        a1Words.put("oyun", "game");
        a1Words.put("müze", "museum");
        a1Words.put("park", "park");
        a1Words.put("plaj", "beach");
        a1Words.put("göl", "lake");
        a1Words.put("nehir", "river");
        a1Words.put("orman", "forest");
        a1Words.put("çiçek", "flower");
        a1Words.put("balık", "fish");
        return a1Words;
    }
}
