package level;

import java.util.HashMap;
import java.util.Map;

public class A2Words {
    public static Map<String, String> getWords() {
        Map<String, String> a2Words = new HashMap<>();
        a2Words.put("bisiklet", "bicycle");
        a2Words.put("film", "movie");
        a2Words.put("yüzme", "swimming");
        a2Words.put("gitar", "guitar");
        a2Words.put("balık", "fish");
        a2Words.put("flower", "çiçek");
        a2Words.put("gözlük", "glasses");
        a2Words.put("beautiful", "güzel");
        a2Words.put("saat", "watch");
        a2Words.put("şehir", "city");
        a2Words.put("yemek", "food");
        a2Words.put("öğrenci", "student");
        a2Words.put("bookshelf", "kitaplık");
        a2Words.put("painting", "resim");
        a2Words.put("müzik", "music");
        a2Words.put("tatil", "holiday");
        a2Words.put("yazı", "writing");
        a2Words.put("kar", "snow");
        a2Words.put("walking", "yürüyüş");
        a2Words.put("kış", "winter");
        a2Words.put("bahar", "spring");
        a2Words.put("hava", "weather");
        a2Words.put("shoe", "ayakkabı");
        a2Words.put("sunglasses", "güneş gözlüğü");
        a2Words.put("gazete", "newspaper");
        a2Words.put("kahve", "coffee");
        a2Words.put("teacher", "öğretmen");
        a2Words.put("bilgisayar oyunu", "video game");
        a2Words.put("meyve", "fruit");
        a2Words.put("pizza", "pizza");
        a2Words.put("newspaper", "gazete");
        a2Words.put("internet", "internet");
        a2Words.put("kayak", "skiing");
        a2Words.put("library", "kütüphane");
        a2Words.put("yol", "road");
        a2Words.put("uçak", "airplane");
        a2Words.put("hotel", "otel");
        a2Words.put("gölge", "shadow");
        a2Words.put("gün", "day");
        a2Words.put("hasta", "sick");
        a2Words.put("health", "sağlık");
        a2Words.put("gül", "rose");
        a2Words.put("diş", "tooth");
        a2Words.put("güneşlik", "sunshade");
        a2Words.put("gemi", "ship");
        a2Words.put("ayakkabı", "shoe");
        a2Words.put("sunburn", "güneş yanığı");
        a2Words.put("gece", "night");
        a2Words.put("resim", "picture");
        a2Words.put("güzel", "beautiful");
        a2Words.put("bulut", "cloud");
        a2Words.put("wrong", "yanlış");
        a2Words.put("doğru", "correct");
        a2Words.put("yavaş", "slow");
        a2Words.put("fast", "hızlı");
        a2Words.put("festival", "festival");
        a2Words.put("dancing", "dans");
        a2Words.put("exercise", "egzersiz");
        a2Words.put("hat", "şapka");
        a2Words.put("dance", "dans etmek");
        a2Words.put("vegetable", "sebze");
        a2Words.put("river", "nehir");
        a2Words.put("mountain", "dağ");
        a2Words.put("ocean", "okyanus");
        a2Words.put("lake", "göl");
        a2Words.put("dessert", "tatlı");
        a2Words.put("rainy", "yağmurlu");
        a2Words.put("sunny", "güneşli");
        a2Words.put("windy", "rüzgarlı");
        a2Words.put("cloudy", "bulutlu");
        a2Words.put("warm", "ılıman");
        a2Words.put("cold", "soğuk");
        a2Words.put("hot", "sıcak");
        a2Words.put("freezing", "donmak");
        a2Words.put("swim", "yüzmek");
        a2Words.put("watch TV", "televizyon izlemek");
        a2Words.put("listen to music", "müzik dinlemek");
        a2Words.put("go shopping", "alışverişe gitmek");
        a2Words.put("visit a museum", "bir müzeyi ziyaret etmek");
        a2Words.put("play a game", "oyun oynamak");
        a2Words.put("ride a bike", "bisiklet sürmek");

        return a2Words;
    }
}
