package level;

import java.util.HashMap;
import java.util.Map;

public class B2Words {
    public static Map<String, String> getWords() {
        Map<String, String> b2Words = new HashMap<>();
        b2Words.put("şiddet", "violence");
        b2Words.put("ölçmek", "measure");
        b2Words.put("statistics", "istatistik");
        b2Words.put("vazgeçmek", "give up");
        b2Words.put("mostly", "çoğunlukla");
        b2Words.put("istek", "request");
        b2Words.put("zorluk", "difficulty");
        b2Words.put("improve", "geliştirmek");
        b2Words.put("değer", "value");
        b2Words.put("farklı", "different");
        b2Words.put("önemli", "important");
        b2Words.put("serbest", "free");
        b2Words.put("meeting", "toplantı");
        b2Words.put("gereksiz", "unnecessary");
        b2Words.put("başarılı", "successful");
        b2Words.put("comprehend", "anlamak");
        b2Words.put("yararlı", "useful");
        b2Words.put("unutmak", "forget");
        b2Words.put("over time", "zamanla");
        b2Words.put("engel", "obstacle");
        b2Words.put("responsible", "sorumlu");
        b2Words.put("temel", "fundamental");
        b2Words.put("görüş", "opinion");
        b2Words.put("açıklamak", "explain");
        b2Words.put("öne çıkan", "prominent");
        b2Words.put("karşılaşmak", "encounter");
        b2Words.put("accept", "kabul etmek");
        b2Words.put("bilgi", "information");
        b2Words.put("doğal", "natural");
        b2Words.put("technology", "teknoloji");
        b2Words.put("kültür", "culture");
        b2Words.put("karar", "decision");
        b2Words.put("independence", "bağımsızlık");
        b2Words.put("tüketici", "consumer");
        b2Words.put("gerçek", "real");
        b2Words.put("toplum", "community");
        b2Words.put("organizasyon", "organization");
        b2Words.put("progress", "gelişme");
        b2Words.put("eleştiri", "criticism");
        b2Words.put("çözüm", "solution");
        b2Words.put("ilişki", "relationship");
        b2Words.put("hükümet", "government");
        b2Words.put("philosophy", "felsefe");
        b2Words.put("modern", "modern");
        b2Words.put("gizli", "secret");
        b2Words.put("mücadele", "struggle");
        b2Words.put("karışık", "complicated");
        b2Words.put("requirement", "gereklilik");
        b2Words.put("davranış", "behavior");
        b2Words.put("fırsat", "opportunity");
        b2Words.put("anı", "moment");
        b2Words.put("constant", "sürekli");
        b2Words.put("genişletmek", "expand");
        b2Words.put("kolaylaştırmak", "facilitate");
        b2Words.put("advance", "ilerleme");
        b2Words.put("gizlilik", "privacy");
        b2Words.put("perfect", "mükemmel");
        b2Words.put("objective", "hedef");
        b2Words.put("neglect", "ihmal etmek");
        b2Words.put("deviation", "sapma");
        b2Words.put("allocate", "ayırmak");
        b2Words.put("indicate", "belirtmek");
        b2Words.put("justify", "haklı çıkarmak");
        b2Words.put("irrelevant", "ilgisiz");
        b2Words.put("overcome", "üstesinden gelmek");
        b2Words.put("attribute", "atfetmek");
        b2Words.put("dedicate", "adamak");
        b2Words.put("advocate", "savunmak");
        b2Words.put("exemplify", "örneklemek");
        b2Words.put("fluctuate", "dalgalanmak");
        b2Words.put("implement", "uygulamak");
        b2Words.put("mediate", "aracılık etmek");
        b2Words.put("perceive", "algılamak");
        b2Words.put("resemble", "benzemek");
        b2Words.put("stimulate", "uyarmak");
        b2Words.put("undermine", "zayıflatmak");
        b2Words.put("validate", "doğrulamak");
        b2Words.put("warrant", "garanti etmek");
        b2Words.put("yield", "verim");
        b2Words.put("abandon", "terk etmek");
        b2Words.put("benevolent", "hayırsever");
        b2Words.put("candid", "samimi");
        b2Words.put("diligent", "gayretli");
        b2Words.put("elusive", "elde edilmesi zor");
        b2Words.put("futile", "boşuna");
        b2Words.put("gratuitous", "bedelsiz");
        b2Words.put("harmonious", "uyumlu");
        b2Words.put("impulsive", "düşüncesiz");
        b2Words.put("jubilant", "sevinçli");
        b2Words.put("meticulous", "titiz");
        b2Words.put("nomadic", "göçebe");
        b2Words.put("oblivious", "aldırışsız");
        b2Words.put("pervasive", "her yere yayılmış");
        b2Words.put("quizzical", "şaşkın");
        b2Words.put("resilient", "dayanıklı");
        b2Words.put("stoic", "duygusuz");
        b2Words.put("taciturn", "suskun");
        b2Words.put("ubiquitous", "heryerde bulunan");
        b2Words.put("vociferous", "gürültülü");
        b2Words.put("wary", "şüpheli");
        b2Words.put("zenith", "zenit");

        return b2Words;
    }
}
