package level;

import java.util.HashMap;
import java.util.Map;

public class C2Words {
    public static Map<String, String> getWords() {
        Map<String, String> c2Words = new HashMap<>();
        c2Words.put("alert", "uyarmak");
        c2Words.put("amendment", "değişiklik");
        c2Words.put("burden", "yük");
        c2Words.put("cautious", "temkinli");
        c2Words.put("declaration", "beyan");
        c2Words.put("detaylandırmak", "elaborate");
        c2Words.put("embody", "somutlaştırmak");
        c2Words.put("enquiry", "soruşturma");
        c2Words.put("equivalent", "eşdeğer");
        c2Words.put("execute", "yürütmek");
        c2Words.put("exemption", "muafiyet");
        c2Words.put("sömürmek", "exploit");
        c2Words.put("expose", "maruz bırakmak");
        c2Words.put("fine", "ceza kesmek");
        c2Words.put("bakış", "gaze");
        c2Words.put("generate", "üretmek");
        c2Words.put("genre", "tür");
        c2Words.put("gradual", "kademeli");
        c2Words.put("grain", "tahıl");
        c2Words.put("hardware", "donanım");
        c2Words.put("uygulama", "implementation");
        c2Words.put("incentive", "teşvik");
        c2Words.put("inflict", "zarar vermek");
        c2Words.put( "müdahale etmek","interfere");
        c2Words.put("interpret", "yorumlamak");
        c2Words.put("interval", "aralık");
        c2Words.put("leak", "sızıntı");
        c2Words.put("leap", "sıçramak");
        c2Words.put("manner", "tavır");
        c2Words.put("monetary", "parasal");
        c2Words.put("municipal", "belediyeye ait");
        c2Words.put("belirsiz", "obscure");
        c2Words.put("occasion", "fırsat");
        c2Words.put("occurrence", "oluşum");
        c2Words.put("emekli maaşı", "pension");
        c2Words.put("ısrar etmek", "persist");
        c2Words.put("sahip olmak", "possess");
        c2Words.put("praise", "övmek");
        c2Words.put("precede", "önce gelmek");
        c2Words.put("precise", "kesin");
        c2Words.put("premises", "dayanak noktaları");
        c2Words.put("korumak", "preserve");
        c2Words.put("presumably", "muhtemelen");
        c2Words.put("primitive", "ilkel");
        c2Words.put("probe", "araştırmak");
        c2Words.put("productivity", "verimlilik");
        c2Words.put("prompt", "çabuk");
        c2Words.put("reckon", "saymak");
        c2Words.put("benzemek", "resemble");
        c2Words.put("residue", "kalıntı");
        c2Words.put("retain", "alıkoymak");
        c2Words.put("gözden geçirmek", "revise");
        c2Words.put("scatter", "saçmak");
        c2Words.put("tortu", "sediment");
        c2Words.put("severe", "şiddetli");
        c2Words.put("sheer", "katıksız");
        c2Words.put("smash", "paramparça etmek");
        c2Words.put("specimen", "numune");
        c2Words.put("kanuni", "statutory");
        c2Words.put("subsequent", "sonraki");
        c2Words.put("subtle", "inceden");
        c2Words.put("suffix", "son ek");
        c2Words.put("underlie", "altında yatmak");
        c2Words.put("utterly", "tamamen");
        c2Words.put("vegetation", "bitki örtüsü");
        c2Words.put("velocity", "hız");
        c2Words.put("arbitrary", "keyfi");
        c2Words.put("assert", "iddia etmek");
        c2Words.put("conceal", "gizlemek");
        c2Words.put("contemplate", "düşünüp taşımak");
        c2Words.put("deter", "caydırmak");
        c2Words.put("deviate", "sapmak");
        c2Words.put("diminish", "azaltmak");
        c2Words.put("encompass", "kuşatmak");
        c2Words.put("endure", "dayanmak");
        c2Words.put("exacerbate", "kötüleştirmek");
        c2Words.put("forge", "demir dövmek");
        c2Words.put("harbor", "barındırmak");
        c2Words.put("incorporate", "bünyesine katmak");
        c2Words.put("integrate", "bütünleştirmek");
        c2Words.put("mitigate", "hafifletmek");
        c2Words.put("neglect", "ihmal etmek");
        c2Words.put("perpetuate", "sürdürmek");
        c2Words.put("prohibit", "yasaklamak");
        c2Words.put("revoke", "iptal etmek");
        c2Words.put("stifle", "bastırmak");
        c2Words.put("transcend", "aşmak");
        c2Words.put("undermine", "zayıflatmak");
        c2Words.put("uphold", "desteklemek");
        c2Words.put("validate", "onaylamak");
        c2Words.put("adhere", "bağlı kalmak");
        c2Words.put("allege", "ileri sürmek");
        c2Words.put("ameliorate", "iyileştirmek");
        c2Words.put("annihilate", "imha etmek");
        c2Words.put("aspire", "arzu etmek");
        c2Words.put("bemoan", "üzüntü duymak");
        c2Words.put("circumvent", "kaçınmak");
        c2Words.put("coalesce", "birleşmek");
        c2Words.put("construe", "yorumlamak");
        c2Words.put("debilitate", "zayıflatmak");
        c2Words.put("deplore", "üzülmek");
        c2Words.put("disparage", "küçümsemek");
        c2Words.put("elicit", "ortaya çıkarmak");
        c2Words.put("exasperate", "çileden çıkarmak");
        c2Words.put("facilitate", "kolaylaştırmak");
        c2Words.put("galvanize", "teşvik etmek");
        c2Words.put("heighten", "artırmak");
        c2Words.put("imbue", "doldurmak");
        c2Words.put("juxtapose", "yan yana koymak");
        c2Words.put("lament", "yakınmak");
        c2Words.put("magnify", "büyütmek");
        c2Words.put("nullify", "geçersiz kılmak");
        c2Words.put("obstruct", "engellemek");
        c2Words.put("perish", "mahvolmak");
        c2Words.put("quell", "bastırmak");
        c2Words.put("relinquish", "vazgeçmek");
        c2Words.put("seclude", "izole etmek");
        c2Words.put("temper", "hafifletmek");
        c2Words.put("undercut", "zarar vermek");
        c2Words.put("vacillate", "kararsızlık göstermek");
        c2Words.put("warrant", "garanti etmek");
        c2Words.put("yield", "verim sağlamak");
        c2Words.put("zenith", "zirve");
        return c2Words;
    }
}
