package level;

import java.util.HashMap;
import java.util.Map;
import java.util.Random;

public class SentenceGenerator {

    private static final Map<String, String> sentences = new HashMap<>();

    static {
        sentences.put("New places spark the flame of adventure in the heart.", "Yeni yerler, maceranın kalpte ateşini yakar.");
        sentences.put("Imagination paints the world with endless colors.", "Hayal gücü, dünyayı sonsuz renklerle boyar.");
        sentences.put("Courage is a small voice saying, 'I will try again tomorrow.'", "Cesaret, 'Yarın tekrar deneyeceğim' diyen küçük bir ses.");
        sentences.put("In nature, harmony is the silent music of existence.", "Doğada, uyum varlığın sessiz müziğidir.");
        sentences.put("Curiosity is the compass that leads to discovery.", "Merak, keşfe yol gösteren pusuladır.");
        sentences.put("Happiness is a cup of tea and a good book on a rainy day.", "Mutluluk, yağmurlu bir günde bir fincan çay ve iyi bir kitaptır.");
        sentences.put("Wisdom is the echo of experience.", "Bilgelik, deneyimin yankısıdır.");
        sentences.put("The mirror reflects the outer, but the heart reflects the inner.", "Ayna dışarıyı yansıtır, ancak kalp içeriyi yansıtır.");
        sentences.put("Every journey begins with a single step.", "Her yolculuk, tek bir adımla başlar.");
        sentences.put("Freedom is the wings that let the heart soar.", "Özgürlük, kalbin yükselmesine izin veren kanatlardır.");
        sentences.put("Hope is the sunrise after the darkest night.", "Umut, en karanlık gecenin ardından doğan güneştir.");
        sentences.put("Adventure is the heartbeat of a life well-lived.", "Macera, iyi yaşanmış bir yaşamın kalp atışıdır.");
        sentences.put("Discovery is the joy of finding treasures in unexpected places.", "Keşif, beklenmedik yerlerde hazineler bulmanın sevincidir.");
        sentences.put("Harmony is the dance of elements creating a symphony of existence.", "Uyum, elementlerin dansıyla varoluşun senfonisini oluşturur.");
        sentences.put("Freedom is the wind beneath the wings of the soul.", "Özgürlük, ruhun kanatlarının altındaki rüzgardır.");
        sentences.put("Hope is the anchor that keeps the soul grounded in storms.", "Umut, ruhu fırtınalarda yerinde tutan çapa gibidir.");
        sentences.put("Curiosity is the key that unlocks the doors to endless possibilities.", "Merak, sonsuz olasılıkların kapılarını açan anahtardır.");
        sentences.put("Laughter is the music of the heart that needs no translation.", "Kahkaha, tercüme gerektirmeyen kalbin müziğidir.");
        sentences.put("Silence is the language of understanding between kindred spirits.", "Sessizlik, benzer ruhların anlayış dilidir.");
        sentences.put("Patience is the bridge that connects frustration to success.", "Sabır, hayal kırıklığını başarıya bağlayan köprüdür.");
        sentences.put("In the tapestry of life, every thread contributes to the beauty of the whole.", "Hayatın dokuma tablosunda her iplik, bütünün güzelliğine katkıda bulunur.");
        sentences.put("Laughter is the sunshine that chases away the clouds of gloom.", "Kahkaha, karanlık bulutları kovalayan güneştir.");
        sentences.put("Friendship is the compass that guides us through the storms of life.", "Dostluk, bizi hayatın fırtınalarında yönlendiren pusuladır.");
        sentences.put("Love is the universal language spoken by the heart.", "Aşk, kalp tarafından konuşulan evrensel bir dildir.");
        sentences.put("Kindness is the bridge that connects hearts across differences.", "İyilik, farklılıklar arasında kalpleri birleştiren köprüdür.");
        sentences.put("Success is the result of persistence and unwavering determination.", "Başarı, sürekli çaba ve kararlılık sonucudur.");
        sentences.put("Knowledge is the light that dispels the darkness of ignorance.", "Bilgi, cehaletin karanlığını dağıtan ışıktır.");
        sentences.put("Dreams are the stars that light up the night sky of possibilities.", "Rüyalar, olasılıkların gece gökyüzünü aydınlatan yıldızlardır.");
        sentences.put("Gratitude is the magic key that opens the door to happiness.", "Minnettarlık, mutluluğun kapısını açan sihirli bir anahtardır.");
        sentences.put("Passion is the fuel that drives us towards our deepest desires.", "Tutku, bizi en derin arzularımıza doğru yönlendiren yakıttır.");
        sentences.put("Resilience is the strength that helps us bounce back from life's challenges.", "Dayanıklılık, hayatın zorluklarından geri dönmamıza yardımcı olan bir güçtür.");
        sentences.put("Balance is the key to a harmonious and fulfilling life.", "Denge, uyumlu ve tatmin edici bir yaşamın anahtarıdır.");
        sentences.put("Time is the precious currency that we spend, so spend it wisely.", "Zaman, harcadığımız değerli bir paradır, bu nedenle onu akıllıca harcayın.");
        sentences.put("Adversity is the stepping stone to strength and resilience.", "Zorluklar, güç ve dayanıklılığa giden basamaklardır.");
        sentences.put("Forgiveness is the gift we give ourselves to heal and move forward.", "Bağışlama, iyileşmek ve ileri gitmek için kendimize verdiğimiz bir hediyedir.");
        sentences.put("Nature is the greatest artist, painting landscapes with breathtaking beauty.", "Doğa, nefes kesen güzellikte manzaraları resmeden en büyük sanatkârdır.");
        sentences.put("Success is not just about reaching the destination but enjoying the journey.", "Başarı, sadece varış noktasına ulaşmak değil, yolculuğun tadını çıkarmaktır.");
        sentences.put("Courage is the spark that ignites when facing the unknown.", "Cesaret, bilinmeyenle yüzleşildiğinde ateşlenen kıvılcımdır.");
        sentences.put("In the garden of life, kindness is the most beautiful flower.", "Hayatın bahçesinde, iyilik en güzel çiçektir.");
        sentences.put("Perseverance is the bridge between goals and their achievement.", "Azim, hedefler ile onların gerçekleşmesi arasındaki köprüdür.");
        sentences.put("Success is the sum of small efforts repeated day in and day out.", "Başarı, gün be gün tekrarlanan küçük çabaların toplamıdır.");
        sentences.put("Challenges are the stepping stones that lead to growth and strength.", "Zorluklar, büyüme ve güce götüren basamaklardır.");
        sentences.put("Joy is the simplest form of gratitude.", "Sevinç, minnettarlığın en basit hali.");
        sentences.put("Hope is the heartbeat of the soul in times of uncertainty.", "Umut, belirsiz zamanlarda ruhun kalp atışıdır.");
        sentences.put("Generosity is the art of giving without expecting anything in return.", "Cömertlik, karşılık beklemeden vermenin sanatıdır.");
        sentences.put("Adventure is not in the guidebook, and beauty is not on the map.", "Macera rehber kitapta değil, güzellik haritada değil.");
        sentences.put("Patience is not the ability to wait but the ability to keep a good attitude while waiting.", "Sabır, beklemek değil, beklerken iyi bir tutum tutma yeteneğidir.");
        sentences.put("The best way to predict the future is to create it.", "Geleceği tahmin etmenin en iyi yolu, onu yaratmaktır.");
        sentences.put("Life is short; live it to the fullest.", "Hayat kısa; onu en dolu dolu yaşayın.");
        sentences.put("Success is not final, failure is not fatal: It is the courage to continue that counts.", "Başarı nihai değildir, başarısızlık ölümcül değildir: Devam etme cesareti önemlidir.");
        sentences.put("The only limit to our realization of tomorrow will be our doubts of today.", "Yarının farkına varma sınırlarımız, bugünkü şüphelerimiz olacaktır.");
        sentences.put("The only way to do great work is to love what you do.", "Harika işler yapmanın tek yolu, yaptığınız işi sevmektir.");
        sentences.put("Your time is limited, don't waste it living someone else's life.", "Zamanınız sınırlıdır, onu başkasının yaşamını yaşayarak boşa harcamayın.");
        sentences.put("Don't watch the clock; do what it does. Keep going.", "Saatı izleme; o ne yapıyorsa onu yap. Devam et.");
        sentences.put("The only thing standing between you and your goal is the story you keep telling yourself.", "Seni hedefine ulaştıran tek şey, kendine anlatmaya devam ettiğin hikayedir.");
        sentences.put("Believe you can and you're halfway there.", "İnanabilirsen yarı yolda gibisin.");
        sentences.put("It always seems impossible until it's done.", "Her zaman imkansız görünür, ta ki yapılıncaya kadar.");
        sentences.put("You are never too old to set another goal or to dream a new dream.", "Başka bir hedef koymak veya yeni bir hayal kurmak için asla çok yaşlı değilsin.");
        sentences.put("The only way to achieve the impossible is to believe it is possible.", "İmkansızı başarmak için tek yol, bunun mümkün olduğuna inanmaktır.");
        sentences.put("Success is stumbling from failure to failure with no loss of enthusiasm.", "Başarı, başarısızlıktan başarısızlığa tökezleme yeteneğiyle kaybolmayan bir hevesle ilgilidir.");
        sentences.put("The future belongs to those who believe in the beauty of their dreams.", "Gelecek, hayallerinin güzelliğine inananlara aittir.");
        sentences.put("Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", "Zihnindeki korkular tarafından itilmeyin. Kalbindeki hayaller tarafından yönlendirilin.");
        sentences.put("Time flies when you're having fun.", "Eğlenirken zaman hızla geçer.");
        sentences.put("Actions speak louder than words.", "Eylemler sözlerden daha etkilidir.");
        sentences.put("Every cloud has a silver lining.", "Her bulutun bir gümüş yaldızı vardır.");
        sentences.put("When life gives you lemons, make lemonade.", "Hayat size limon verdiğinde, limonata yapın.");
        sentences.put("Don't count your chickens before they hatch.", "Yumurtadan çıkmadan tavukları sayma.");
        sentences.put("All that glitters is not gold.", "Parlayan her şey altın değildir.");
        sentences.put("Better late than never.", "Geç olsun güç olmasın.");
        sentences.put("Where there's a will, there's a way.", "İstediğiniz bir şey için bir yol bulabilirsiniz.");
        sentences.put("Don't put all your eggs in one basket.", "Bütün yumurtalarınızı aynı sepete koymayın.");
        sentences.put("Every dog has its day.", "Her köpeğin bir günü vardır.");
        sentences.put("A picture is worth a thousand words.", "Bir resim bin kelimeye bedeldir.");
        sentences.put("You can't judge a book by its cover.", "Bir kitabı kapağına göre yargılayamazsınız.");
        sentences.put("When in Rome, do as the Romans do.", "Romalılar gibi Romalılar gibi yap.");
        sentences.put("Don't cry over spilled milk.", "Dökülen süt için ağlama.");
        sentences.put("Rome wasn't built in a day.", "Roma bir günde inşa edilmedi.");
        sentences.put("All is fair in love and war.", "Aşkta ve savaşta her şey mübahtır.");
        sentences.put("Don't bite the hand that feeds you.", "Sizi besleyen eli ısırma.");
        sentences.put("The early bird catches the worm.", "Erken kalkan kuş solucanı yakalar.");
        sentences.put("A watched pot never boils.", "İzlenen tencere asla kaynamaz.");
        sentences.put("Two wrongs don't make a right.", "İki yanlış bir doğru yapmaz.");
        sentences.put("Haste makes waste.", "Acele işe şeytan karışır.");
        sentences.put("The grass is always greener on the other side.", "Komşunun çimenleri her zaman daha yeşildir.");
        sentences.put("Every rose has its thorn.", "Her gülün dikeni vardır.");
        sentences.put("When the going gets tough, the tough get going.", "Zorlaştığında, güçlüler devam eder.");
        sentences.put("Easy come, easy go.", "Kolay kazan, kolay kaybolur.");
        sentences.put("Beggars can't be choosers.", "Dilenciler seçici olamaz.");
        sentences.put("The more, the merrier.", "Ne kadar çok, o kadar neşeli.");
        sentences.put("It's a piece of cake.", "Bu çocuk oyuncağı.");
        sentences.put("All talk and no action.", "Sadece laf, hiç iş yok.");
        sentences.put("Success is not how high you have climbed, but how you make a positive difference to the world.", "Başarı, ne kadar yüksek tırmandığınız değil, dünyaya olumlu bir fark yaratma şeklinizdir.");
    }
}